# Generated by Django 2.2.2 on 2019-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblio',
            name='nbc',
            field=models.CharField(max_length=31, primary_key=True, serialize=False, verbose_name='NBC(全国書誌番号)'),
        ),
    ]
